[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
futures-util = "0.3.30"
jsonwebtoken = "9.3.0"
serde = "1.0.204"
surrealdb = "1.5.4"
